title: "Gabriel Melo – Data Analyst"
author: Gabriel Melo
email: gabrielcm@duck.com
description: >
  Portfolio of Gabriel Melo, Data Analyst with skills in Python, Web Scraping, Digital Analytics, and Automation.
theme: jekyll/minima
minima:
  skin: auto
  social_links:
    github: melogabriel
    linkedin: gabriel-melo
plugins:
  - jekyll-feed